# === Bounty Rules ===
bounty:
  min-amount: 100.0
  max-amount: 100000.0
  placement-fee:
    enabled: true
    amount: 50.0
  stacking:
    enabled: true # true: Allows players to add onto an existing bounty, increasing its total amount
  expiration:
    enabled: true
    time: 7d # 7 days; supports h/m/s/d notation
  anonymous:
    enabled: true
  claim-own-bounty: false

# === Player Opting-In/Out Settings ===

auto-opt-out-on-first-join: true # Automatically opts players out of being a bounty target on their first join
opt-in:
  cooldown:
    time: 30d
    count-only-while-online: true # true: Only reduce cooldown while player is online

opt-out:
  cooldown:
    time: 30d
    count-only-while-online: true

# === Player Head Drop ===
head-drop:
  enabled: true
  item:
    name: "&e%player%'s Head"
    lore:
      - "&eClaimed by &4%killer% &efor &a$%amount%"

# === Staff Settings ===
staff:
  can-edit-bounties: true # Permission: hitlist.bounty.edit.others
  refund-on-removal: true

# === Leaderboards Settings ===
leaderboards:
  refresh-interval: 5m # 5 minutes