# === Bounty Rules ===
bounty:
  min-amount: 100.0
  max-amount: 100000.0
  placement-fee:
    enabled: true
    amount: 50.0
  stacking:
    enabled: true
  expiration:
    enabled: true
    time: 7d # 7 days; supports h/m/s/d notation
  anonymous:
    enabled: true

# === Player Opting-In/Out Settings ===
opt-in:
  cooldown:
    time: 30d
    count-only-while-online: true

opt-out:
  cooldown:
    time: 30d
    count-only-while-online: true

# === Claim Settings ===
claim:
  cooldown:
    enabled: true
    time: 10s # Prevent spam

# === Player Head Drop ===
head-drop:
  enabled: true

# === Staff Settings ===
staff:
  can-edit-bounties: true # Permission: hitlist.bounty.edit.others
  refund-on-removal: true

# === Economy ===
economy:
  plugin: Vault
  integration-enabled: true